import React, { useState } from 'react';
import {
  Server,
  Sliders,
  Code,
  CheckCircle2,
  Plus,
  Save,
  Cpu,
  Layers,
  ShieldAlert,
  Smartphone,
  Info,
  RefreshCw
} from 'lucide-react';
import { MinecraftServer, ServerType } from '../types';

interface ServerManagerViewProps {
  activeServer: MinecraftServer;
  onUpdateServerProps: (props: Partial<MinecraftServer>) => void;
  onOpenNewServerModal: () => void;
}

export const ServerManagerView: React.FC<ServerManagerViewProps> = ({
  activeServer,
  onUpdateServerProps,
  onOpenNewServerModal,
}) => {
  const [editorTab, setEditorTab] = useState<'visual' | 'raw'>('visual');
  const [saveSuccess, setSaveSuccess] = useState(false);

  // Form State
  const [motd, setMotd] = useState(activeServer.motd);
  const [maxPlayers, setMaxPlayers] = useState(activeServer.maxPlayers);
  const [viewDistance, setViewDistance] = useState(activeServer.viewDistance);
  const [simulationDistance, setSimulationDistance] = useState(activeServer.simulationDistance);
  const [pvp, setPvp] = useState(activeServer.pvpEnabled);
  const [difficulty, setDifficulty] = useState(activeServer.difficulty);
  const [geyserEnabled, setGeyserEnabled] = useState(activeServer.geyserBridgeEnabled);

  const supportedPlatforms: { type: ServerType; name: string; desc: string; isSupported: boolean; badge?: string }[] = [
    { type: 'Paper', name: 'Paper MC', desc: 'Ultra high performance Java server with plugin ecosystem.', isSupported: true, badge: 'Recommended' },
    { type: 'Purpur', name: 'Purpur', desc: 'Fork of Paper with custom gameplay toggles & performance tweaks.', isSupported: true },
    { type: 'Spigot', name: 'Spigot', desc: 'Classic Minecraft plugin platform with high plugin compatibility.', isSupported: true },
    { type: 'Vanilla', name: 'Vanilla', desc: 'Official Mojang server software. Zero mods or plugins.', isSupported: true },
    { type: 'Fabric', name: 'Fabric', desc: 'Lightweight, modern modding framework (Sodium, Iris, Lithium).', isSupported: true },
    { type: 'Forge', name: 'Forge', desc: 'Classic modded server ecosystem for large modpacks.', isSupported: true },
    { type: 'Bedrock', name: 'Bedrock', desc: 'Official Minecraft Bedrock server for mobile, Xbox, & Switch.', isSupported: true },
    { type: 'Geyser Bridge', name: 'Geyser Bridge', desc: 'Seamless cross-play bridge joining Bedrock players into Java.', isSupported: true, badge: 'Cross-Play' },
  ];

  const handleSaveConfig = () => {
    onUpdateServerProps({
      motd,
      maxPlayers,
      viewDistance,
      simulationDistance,
      pvpEnabled: pvp,
      difficulty,
      geyserBridgeEnabled: geyserEnabled,
    });
    setSaveSuccess(true);
    setTimeout(() => setSaveSuccess(false), 3000);
  };

  const rawPropertiesText = `# Minecraft server.properties generated by JB³ GameHub
# ${new Date().toISOString()}
motd=${motd}
max-players=${maxPlayers}
view-distance=${viewDistance}
simulation-distance=${simulationDistance}
pvp=${pvp}
difficulty=${difficulty}
online-mode=true
enable-rcon=true
rcon.port=25575
server-port=${activeServer.port}
level-name=world
allow-flight=false
spawn-protection=16
geyser.enabled=${geyserEnabled}
geyser.bedrock-port=${activeServer.bedrockPort || 19132}`;

  return (
    <div className="space-y-8 pb-12 animate-in fade-in duration-200">
      {/* Header Banner */}
      <div className="bg-[#18181b] border border-zinc-800 p-6 md:p-8 rounded-3xl shadow-xl flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <Server className="w-6 h-6 text-emerald-400" />
            <h1 className="text-2xl font-black text-zinc-100 tracking-tight">Server Manager & Engine Config</h1>
          </div>
          <p className="text-xs text-zinc-400 mt-1 font-mono">
            Manage Minecraft engines, server types, versions, and <code className="text-emerald-400 font-bold">server.properties</code> configurations.
          </p>
        </div>

        <button
          onClick={onOpenNewServerModal}
          className="px-5 py-3 bg-emerald-500 hover:bg-emerald-400 text-[#09090b] font-black rounded-xl text-xs flex items-center gap-2 transition-all shadow-[0_0_15px_rgba(16,185,129,0.2)]"
        >
          <Plus className="w-4 h-4" />
          Deploy New Server
        </button>
      </div>

      {/* Supported Server Types Grid */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="text-xs font-bold text-zinc-400 uppercase tracking-widest font-mono flex items-center gap-2">
            <Layers className="w-4 h-4 text-emerald-400" /> Supported Minecraft Server Engines
          </h2>
          <span className="text-xs text-zinc-500 font-mono">8 Available Platforms</span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {supportedPlatforms.map((plat) => {
            const isActive = activeServer.type === plat.type;
            return (
              <div
                key={plat.type}
                className={`p-5 rounded-3xl border transition-all relative flex flex-col justify-between ${
                  isActive
                    ? 'bg-[#18181b] border-emerald-500 shadow-[0_0_20px_rgba(16,185,129,0.15)]'
                    : 'bg-[#18181b] border-zinc-800 hover:border-zinc-700'
                }`}
              >
                {plat.badge && (
                  <span className="absolute top-4 right-4 px-2 py-0.5 text-[9px] font-mono font-bold uppercase tracking-wider text-emerald-400 bg-emerald-950/80 border border-emerald-800 rounded-md">
                    {plat.badge}
                  </span>
                )}

                <div>
                  <div className="flex items-center gap-2 mb-2">
                    <CheckCircle2 className={`w-4 h-4 ${isActive ? 'text-emerald-400' : 'text-zinc-600'}`} />
                    <h3 className="text-sm font-extrabold text-zinc-100">{plat.name}</h3>
                  </div>

                  <p className="text-xs text-zinc-400 leading-relaxed mb-4">
                    {plat.desc}
                  </p>
                </div>

                <div className="pt-3 border-t border-zinc-800/80 flex items-center justify-between font-mono">
                  <span className="text-[10px] text-zinc-500">v1.21.4 Ready</span>
                  {isActive ? (
                    <span className="text-[10px] font-bold text-emerald-400 uppercase tracking-wider">Active Engine</span>
                  ) : (
                    <button
                      onClick={() => onUpdateServerProps({ type: plat.type })}
                      className="text-[10px] font-bold text-zinc-400 hover:text-emerald-400 transition-colors uppercase"
                    >
                      Switch Engine
                    </button>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Interactive server.properties Configurator */}
      <div className="bg-[#18181b] border border-zinc-800 rounded-3xl shadow-xl p-6 md:p-8 space-y-6">
        <div className="flex items-center justify-between flex-wrap gap-4 border-b border-zinc-800 pb-4">
          <div>
            <div className="flex items-center gap-2">
              <Sliders className="w-5 h-5 text-emerald-400" />
              <h2 className="text-base font-bold text-zinc-100">
                <code className="text-emerald-400">server.properties</code> Visual Editor
              </h2>
            </div>
            <p className="text-xs text-zinc-400">
              Editing for <span className="text-zinc-200 font-semibold">{activeServer.name}</span> ({activeServer.type} {activeServer.version})
            </p>
          </div>

          {/* Editor Mode Tabs & Save Button */}
          <div className="flex items-center gap-3">
            <div className="bg-zinc-950 p-1 border border-zinc-800 rounded-xl flex items-center text-xs font-semibold text-zinc-400">
              <button
                onClick={() => setEditorTab('visual')}
                className={`px-3 py-1.5 rounded-lg flex items-center gap-1.5 transition-colors ${
                  editorTab === 'visual' ? 'bg-zinc-800 text-emerald-400' : 'hover:text-zinc-200'
                }`}
              >
                <Sliders className="w-3.5 h-3.5" /> Visual Controls
              </button>
              <button
                onClick={() => setEditorTab('raw')}
                className={`px-3 py-1.5 rounded-lg flex items-center gap-1.5 transition-colors ${
                  editorTab === 'raw' ? 'bg-zinc-800 text-emerald-400' : 'hover:text-zinc-200'
                }`}
              >
                <Code className="w-3.5 h-3.5" /> Raw Code
              </button>
            </div>

            <button
              onClick={handleSaveConfig}
              className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-zinc-950 font-bold rounded-xl text-xs flex items-center gap-1.5 transition-all shadow-md shadow-emerald-600/20"
            >
              <Save className="w-4 h-4" /> Save & Hot Reload
            </button>
          </div>
        </div>

        {saveSuccess && (
          <div className="bg-emerald-950/80 border border-emerald-700/80 p-3 rounded-xl text-xs text-emerald-300 font-semibold flex items-center gap-2 animate-in fade-in duration-150">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            <span><code className="font-mono">server.properties</code> updated successfully! RCON reloaded zero downtime.</span>
          </div>
        )}

        {/* Visual Mode */}
        {editorTab === 'visual' ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {/* MOTD */}
            <div className="space-y-2 col-span-1 md:col-span-2 lg:col-span-3">
              <label className="text-xs font-bold text-zinc-300 uppercase tracking-wider">
                Server MOTD (Message of the Day)
              </label>
              <input
                type="text"
                value={motd}
                onChange={(e) => setMotd(e.target.value)}
                className="w-full bg-zinc-950 border border-zinc-700 focus:border-emerald-500 rounded-xl px-3.5 py-2.5 text-xs text-zinc-100 font-mono outline-none"
              />
              <span className="text-[11px] text-zinc-500">Supports Minecraft § color formatting codes.</span>
            </div>

            {/* Max Players */}
            <div className="space-y-2 bg-zinc-950/60 p-4 border border-zinc-800/80 rounded-xl">
              <div className="flex justify-between items-center">
                <label className="text-xs font-bold text-zinc-300">Max Players Capacity</label>
                <span className="text-xs font-mono font-bold text-emerald-400">{maxPlayers} Slots</span>
              </div>
              <input
                type="range"
                min="5"
                max="200"
                step="5"
                value={maxPlayers}
                onChange={(e) => setMaxPlayers(Number(e.target.value))}
                className="w-full accent-emerald-500 cursor-pointer"
              />
            </div>

            {/* View Distance */}
            <div className="space-y-2 bg-zinc-950/60 p-4 border border-zinc-800/80 rounded-xl">
              <div className="flex justify-between items-center">
                <label className="text-xs font-bold text-zinc-300">View Distance (Render Chunks)</label>
                <span className="text-xs font-mono font-bold text-emerald-400">{viewDistance} Chunks</span>
              </div>
              <input
                type="range"
                min="4"
                max="32"
                step="1"
                value={viewDistance}
                onChange={(e) => setViewDistance(Number(e.target.value))}
                className="w-full accent-emerald-500 cursor-pointer"
              />
            </div>

            {/* Simulation Distance */}
            <div className="space-y-2 bg-zinc-950/60 p-4 border border-zinc-800/80 rounded-xl">
              <div className="flex justify-between items-center">
                <label className="text-xs font-bold text-zinc-300">Simulation Distance (Entity Ticks)</label>
                <span className="text-xs font-mono font-bold text-emerald-400">{simulationDistance} Chunks</span>
              </div>
              <input
                type="range"
                min="3"
                max="16"
                step="1"
                value={simulationDistance}
                onChange={(e) => setSimulationDistance(Number(e.target.value))}
                className="w-full accent-emerald-500 cursor-pointer"
              />
            </div>

            {/* Difficulty */}
            <div className="space-y-2 bg-zinc-950/60 p-4 border border-zinc-800/80 rounded-xl">
              <label className="text-xs font-bold text-zinc-300">World Difficulty</label>
              <select
                value={difficulty}
                onChange={(e) => setDifficulty(e.target.value as any)}
                className="w-full bg-zinc-900 border border-zinc-700 rounded-lg px-3 py-2 text-xs text-zinc-200 outline-none"
              >
                <option value="peaceful">Peaceful</option>
                <option value="easy">Easy</option>
                <option value="normal">Normal</option>
                <option value="hard">Hard</option>
              </select>
            </div>

            {/* PvP Toggle */}
            <div className="space-y-2 bg-zinc-950/60 p-4 border border-zinc-800/80 rounded-xl flex items-center justify-between">
              <div>
                <div className="text-xs font-bold text-zinc-300">Player vs Player (PvP)</div>
                <div className="text-[11px] text-zinc-500">Allow players to attack each other</div>
              </div>
              <button
                type="button"
                onClick={() => setPvp(!pvp)}
                className={`w-12 h-6 rounded-full p-1 transition-colors ${pvp ? 'bg-emerald-600' : 'bg-zinc-800'}`}
              >
                <div className={`w-4 h-4 bg-zinc-100 rounded-full transition-transform ${pvp ? 'translate-x-6' : 'translate-x-0'}`}></div>
              </button>
            </div>

            {/* Geyser Bridge Crossplay Toggle */}
            <div className="space-y-2 bg-zinc-950/60 p-4 border border-zinc-800/80 rounded-xl flex items-center justify-between">
              <div>
                <div className="text-xs font-bold text-zinc-300 flex items-center gap-1.5">
                  <Smartphone className="w-3.5 h-3.5 text-blue-400" /> Geyser Crossplay Bridge
                </div>
                <div className="text-[11px] text-zinc-500">Enable Bedrock / Mobile / Xbox joining</div>
              </div>
              <button
                type="button"
                onClick={() => setGeyserEnabled(!geyserEnabled)}
                className={`w-12 h-6 rounded-full p-1 transition-colors ${geyserEnabled ? 'bg-blue-600' : 'bg-zinc-800'}`}
              >
                <div className={`w-4 h-4 bg-zinc-100 rounded-full transition-transform ${geyserEnabled ? 'translate-x-6' : 'translate-x-0'}`}></div>
              </button>
            </div>
          </div>
        ) : (
          /* Raw Editor Mode */
          <div className="space-y-3 font-mono">
            <textarea
              readOnly
              value={rawPropertiesText}
              rows={14}
              className="w-full bg-zinc-950 border border-zinc-800 rounded-xl p-4 text-xs text-emerald-400 outline-none leading-relaxed shadow-inner"
            ></textarea>
            <p className="text-[11px] text-zinc-500 font-sans">
              To update raw properties, adjust the visual sliders or use the AI Copilot ("Hey JB... set view distance to 12").
            </p>
          </div>
        )}
      </div>
    </div>
  );
};
